ARG FIO_VERSION=3.30-r0
ARG ALPINE_VERSION=3.16.0

FROM alpine:$ALPINE_VERSION

RUN apk --no-cache add fio==$FIO_VERSION

ENV DBENCH_MOUNTPOINT="/data"
ENV FIO_SIZE="2G"
ENV FIO_OFFSET_INCREMENT="500M"
ENV FIO_DIRECT="1"
ENV FIO_RAMP_TIME="2s"
ENV FIO_RUNTIME="15s"
ENV FIO_IOENGINE="libaio"
ENV FIO_IOPS_BS="4K"
ENV FIO_IOPS_IODEPTH="64"
ENV FIO_BW_BS="128K"
ENV FIO_BW_IODEPTH="64"
ENV FIO_LATENCY_BS="4K"
ENV FIO_LATENCY_IODEPTH="4"
ENV FIO_SEQ_BS="1M"
ENV FIO_SEQ_IODEPTH="16"
ENV FIO_MIX_BS="4K"
ENV FIO_MIX_IODEPTH="64"
ENV FIO_MIX_RWMIXREAD="75"

COPY benchmark.sh /usr/local/bin/

CMD ["/usr/local/bin/benchmark.sh"]
